tianocore/edk2-pytool-extensions

edk2toolext/invocables/edk2_ci_build.py, readme.md
Previously, we were using GetGroupName in Junit and instead switched to GetName, which is a bit more standard across CI implementations.
=> [Bug fix] Fixed Junit output by removing GetGroupName

edk2toolext/environment/plugintypes/ci_build_plugin.py, edk2toolext/invocables/edk2_ci_build.py
If a CIBuild plugin can't run because it is missing some prereq then it can return -1 to indicate this to the caller.
=> Change CIBuild plugins to use return code for skipping execution

edk2toolext/environment/var_dict.py, edk2toolext/tests/test_var_dict.py
VarDict has a unique feature in that it can block override of a value.  This is heavily used in the tool and build flow to make sure that settings with high priority are not overridden later in the process by something with lower priority.  Also it is critical for stability that once a value is set and used that it doesn't change.  
But in some cases for specific usage models it might be needed.  The API makes it possible.  
One such example case is in adapting support for Host Based Unit tests and wanted to only compile Host Tests that will run on the host afterwards.
=> Add API to VarDict to alllow override

edk2toolext/invocables/edk2_setup.py
Force setup was failing because Git was trying to remove an open log file.
Add exceptions for the log files and fix a couple of bad working_dir paths that were the copy-pasted wrong.
=> Fix functionality break in Force Setup.

edk2toolext/invocables/edk2_ci_build.py
A current working theory is that the package that a testcase should be under the classname of the testsuite. This helps with that
=> [Bug fix] update package name for JUnit output

edk2toolext/edk2_logging.py
This will catch more things in the compiler output and standardizes it a bit. In the future, this will need to be retooled to catch more types of bugs as it is current very MSVC/EDK2 specific.
Fixes #34
=> [Feature] Reconfiguration of compiler scanning code

edk2toolext/invocables/edk2_ci_build.py
Fixes #15 but basically the argument parsing for -p was using nargs and consuming other arguments. A few solutions were proposed and we elected to use csv and multiple -p arguments
=> [Bug fix] Redid the package argument parsing

docs/_config.yml, edk2toolext/environment/conf_mgmt.py
Check to make sure we actually have a path when we get a result back from VsWhere
=> [Bug] misspelling and non-empty path on VsWhere

edk2toolext/invocables/edk2_pr_eval.py
Logic bug as it did not check if the file was public before triggering dependencies to build.
=> Bug fix: logic to detect public file dependency in pr eval

edk2toolext/environment/uefi_build.py
=> Pass same build variables to DSC parser as to FDF parser.

edk2toolext/capsule/capsule_helper.py, edk2toolext/tests/capsule/capsule_helper_test.py
Fix an issue where normalization is applied to create_inf_file, but not in save_capsule, resulting in inconsistent payload filename, which causes create_cat_file to fail.
=> Fix an issue with inconsistent application of normalization.

.cspell.json, docs/usability/using_firmware_policy_tool.md, edk2toolext/windows/policy/firmware_policy_tool.py
This enables easy creation of policy binaries from the command-line, and
also decoding binary policy files into something understandable
=> Adding a command-line tool for the Windows Firmware Policy Library

azure-pipelines/templates/spell-test-steps.yml, edk2toolext/capsule/pyopenssl_signer.py, edk2toolext/capsule/signtool_signer.py
To the sign() function:
* added type hints
* In parameter dict "signature_options", the key "sign_alg" is
deprecated and replaced with "format".  Its prior value "pkcs12" was
NOT a signature format, it was the format of the signer's
key file. Moving it to a new signer_option key "key_file_format"
* New "signature_option" key "format" supports 1 value of "pkcs7" which
is the true signature format being produced
* Added "format_options" key to parameter dict "signature_options". Values
"embedded" and "detachedSignatureData" are added to distinguish the
different PKCS7 flavors supported.  Note that these format_options
are mutually exclusive
* To ensure compatibility with existing code that passes
"signature_options" with key "pkcs12", sign() detects this and
fills the new parameters with …
=> Add support for _embedded_ PKCS7 signing to signtool_signer sign()

BasicDevTests.py
Only allow lowercase a-z, 0-9, _, /, . in the package and module names.
Some python tools have issues when a "-" is in the package or module name.
=> Add basic test to confirm packages and module names

integration_test/azure-pipelines/windows-robot-integration-test.yml
QEMU fails in the latest builds. This commit pins the QEMU version to a known-good installation.
=> integration_test/azure-pipelines: Pin to a specific QEMU version

edk2toolext/environment/extdeptypes/nuget_dependency.py, edk2toolext/tests/test_nuget_dependency.py, integration_test/azure-pipelines/windows-robot-integration-test.yml
If the Nuget Dependency code finds a cache but cannot
heuristically match the package contents (so that they may
be copied directly) produce a warning to the user that they
may be using a malformed package..
Issue #228
=> nuget_dependency: Warn on malformed cache

edk2toolext/capsule/signtool_signer.py, edk2toolext/tests/test_signtool_signer.py
Also add test cases to cover mutually exclusive options.
=> capsule/signtool_signer: Add support for pkcs7DetachedSignedData

edk2toolext/environment/extdeptypes/nuget_dependency.py
This patch adds robustness to the movement of nuget extdep to its final location. Previous code would occasionally fail and raise issues when the source_dir was not completely removed as part of the call to move. This change splits the copy and the remove, and adds retries to the remove operation.
=> Harden package content move in nuget_dependency fetch

.cspell.json, edk2toolext/environment/extdeptypes/nuget_dependency.py, edk2toolext/tests/test_nuget_dependency.py
As exemplified in nuget versioning site: https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-basics, the current nuget package supports versioning suffixes such as "alpha2", "beta1", etc.
This change added extra logic to support nuget versions suffix with numbers instead of failing to update with "Unparsable version tag".
=> Added logic to support nuget versions suffix with numbers

docs/usability/using_settings_manager.md, docs/using.md
Some minor cleanup on using.md and using_settings_manager.md to make it easier for a new user to navigate.
Notable changes:
- Update hyperlinks
- Simplify "I want to build a platform" section and add links for where to go next
- Use code literals for code things
=> docs: using.md cleanup

edk2toolext/capsule/Readme.md, edk2toolext/capsule/capsule_helper.py, edk2toolext/tests/capsule/capsule_helper_test.py, setup.py
Update CapsuleHeader to check for the 'fw_integrity_file' capsule option and,
if present, set the field in the InfGenerator so that the INF file has the
definitions for the integrity file.
=> capsule: Update CapsuleHelper to process integrity file

.cspell.json, edk2toolext/omnicache.py, edk2toolext/tests/test_omnicache.py
Refactor Omnicache to improve performance, handle tags better, and remove internal yaml config file.
Omnicache version 0.11 design notes:
1. Only a single remote per URL will be permitted.
2. Remote names inside omnicache will be UUIDs generated when a new URL is added.
3. Users may specify names for remotes, but they will be treated simply as "display names" without git significance.
4. As many objects as possible will be cached for any given remote; so all remotes will fetch tags.
4a. To avoid tag name collisions between remotes, tags will be fetched into per-remote namespaces.
5. Older omnicaches will be updated to meet the above design points when first encountered by the script.
5a. This implementation takes care that the underlying git construction is compatible (but not performant) …
=> Refactor OmniCache

edk2toolext/environment/uefi_build.py
This fixes an issue where if you try to skip multiple steps on the cmdline (e.g., `stuart_build --skipprebuild --skipbuild`), only one of the options would be honored. AFAICT, these options don't need to be mutually exclusive, so this PR allows them to be set independently.
=> Allow skipping multiple build steps from the cmdline

edk2toolext/edk2_invocable.py
The formatting of the argument parser epilog wasn't being honored, because argparse strips all the whitespace out by default and does it's own line wrapping. This made the help text very hard to read:
```
<key>=<value> - Set an env variable for the pre/post build process BLD_*_<key>=<value> - Set a build flag for all build types. Key=value will get passed to build
process BLD_<TARGET>_<key>=<value> - Set a build flag for build type of <target> Key=value will get passed to build process for given build type)
```
This PR adds some formatting to make it clearer:
```
positional arguments:
<key>=<value>              - Set an env variable for the pre/post build process
BLD_*_<key>=<value>        - Set a build flag for all build types
(key=value will get passed to build process) …
```
=> Fix formatting of argparse epilog

edk2toolext/bin/nuget.py
Just keeping current given the security sensitive nature of downloading external dependencies.
=> Update NuGet.exe to 5.10.0

integration_test/Shared_Keywords.robot, integration_test/edk2_core_ci.robot, integration_test/edk2_platform_ci.robot, integration_test/edk2_stuart_pr_eval.robot, integration_test/mu_core_ci.robot, integration_test/mu_stuart_pr_eval.robot
This will avoid having to update these tests each time a remote repo changes their default branch.  For Project Mu this happens a lot based on the release process.  For edk2 usage this currently isn't a problem but this change should make it more resiliant to future changes.
Rename "master" and "main" to more correct "default" branch.
=> Update scripts to programmatically find default branch from remote.

edk2toolext/invocables/edk2_ci_build.py, edk2toolext/tests/test_edk2_ci_build.py
Fixed a variable shadowing bug in `merge_config` where the `config` argument was lost.
=> Bug fix in merge_config

edk2toolext/invocables/edk2_ci_build.py
Previous change updated function to be correctly marked as static but didn't update the caller.
=> Bug: Update caller to use correct static method syntax

integration_test/Shared_Keywords.robot, integration_test/mu_core_ci.robot, integration_test/mu_stuart_pr_eval.robot
Integration CI is failing due to agent changes around git configuration.  
Add support for checking the git config and setting user.name and user.email if they are not set.
=> Fix failures in Mu Integration tests due to basecore restructure

edk2toolext/base_abstract_invocable.py, edk2toolext/edk2_invocable.py, edk2toolext/environment/self_describing_environment.py, edk2toolext/invocables/edk2_ci_build.py, edk2toolext/invocables/edk2_platform_build.py, edk2toolext/invocables/edk2_update.py, edk2toolext/tests/test_edk2_update.py, edk2toolext/tests/uefi_tree.py
Adds a GetSkippedDirectories() method that allows a SettingsManager
to specify a tuple of workspace-relative directories that should be
skipped.
This allows subdirectories (such as submodules) that might contain duplicate
resources that would normally cause build errors (such as external dependency
descriptors) to be ignored if only one directory is actually being used for
the current build.
=> Add ability to skip directories

docs/usability/using_image_validation_tool.md, edk2toolext/image_validation.py, edk2toolext/tests/test_image_validation.py, setup.py
Add a PE/COFF image validation tool for command line that can be used to
verify that memory protection requirements such as section alignment and
write / execute exclusion settings have been applied correctly to
PE/COFF files.
=> PE/COFF Image Validation Tool

edk2toolext/environment/extdeptypes/git_dependency.py
[Issue #287]
Change the default behavior for the published path of a git dependency to include the repository root directory. This is needed to reference the repo contents for builds.
Before: ...\MU_BASECORE_extdep
After: ...\MU_BASECORE_extdep\MU_BASECORE
=> Override comput_published_path in git_dependency.py to include repo root

edk2toolext/environment/repo_resolver.py, edk2toolext/invocables/edk2_ci_setup.py, edk2toolext/invocables/edk2_setup.py, edk2toolext/tests/test_edk2_ci_setup.py
Currently, a failure in setup or ci_setup will not cause the pipeline to fail. The only indication
that a failure has occurred would be a failure in later build steps.
This change enables those failures to be detected at the pipeline level.
=> Propagate failures from ci_setup and setup

edk2toolext/environment/self_describing_environment.py, edk2toolext/tests/test_edk2_update.py
161e4be added support to self_describing_environment._gather_env_files()
to skip directories specified by a platform. That commit reused existing
directory walk logic which modifies the dir list used for the walk based
on index.
This does not work when multiple directories might be removed
from a single root as when a directory is removed in-place during
enumeration, the index is incremented by one and the next directory is
removed. This effectively causes the new index to skip the actual next
item on the next iteration.
For example:
dirs = ['.git', 'a', 'b', 'c', 'd']
i = 1
del dirs[i] removes dirs[1] => 'a'
dirs = ['.git', 'b', 'c', 'd']
i = 2
dirs[i] now = 'c' not 'b'
This change modifies the in-place assignment of dirs to use slice
assignment which similarly prunes the dir list for …
=> Bug: Check all directories in env directory traversal

edk2toolext/environment/extdeptypes/git_dependency.py
[Issue #291] 
Downgrade the severity of several log events in GitDependency.verify(). These conditions can occur during a clean build, upgrade of the extdep, or other expected scenarios.
=> Downgrade severity of git dependency verify logging

edk2toolext/edk2_invocable.py
This PR addresses #293 and #294 by updating how packages are removed so that the package path list is not reordered. It also adds in build time verification that there are no nested package paths.
=> Update GetPackagesPath() to prevent package path list reordering

.cspell.json, azure-pipelines/templates/spell-test-steps.yml
This PR Locks Cspell to 5.20.0 and updates the NodeJS Version to 18.X to meet Cspell requirements.
=> Lock CSpell to 5.20.0

edk2toolext/invocables/edk2_ci_setup.py, edk2toolext/tests/test_edk2_ci_setup.py
Fixed a variable name issue in edk2_ci_setup and added a test case to catch it.
=> Fix an issue where a bad variable name caused a trace in an error branch

edk2toolext/environment/extdeptypes/nuget_dependency.py, edk2toolext/tests/test_nuget_dependency.py, requirements.txt
NuGet package versioning is described here:
https://docs.microsoft.com/en-us/nuget/concepts/package-versioning
It follows semantic versioning described here:
https://semver.org/
Among other things, semantic versioning allows an alphanumeric pre-release version number:
https://semver.org/#spec-item-9
The current NuGet versioning normalization code in nuget_dependency.py only permits a limited set of pre-approved tags such as the following to serve as the pre-release version number:
["beta", "alpha", "rc"]
Therefore, a valid NuGet package version string such as the following is considered invalid:
"2.8.4-92" -[reports]-> "ValueError: Unparsable version tag: 92"
In other cases, the previous logic allowed passed invalid versions. For example:
"2.15.05"
Which should not be allowed to use a …
=> Improve NuGet dependency semantic version handling

edk2toolext/environment/extdeptypes/nuget_dependency.py, edk2toolext/tests/test_nuget_dependency.py
Currently, NuGet versions are validated strictly according to the
Semantic Versioning Specification - https://semver.org/.
However, NuGet versions diverge in some ways from Semantic Versioning
as described here:
https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#where-nugetversion-diverges-from-semantic-versioning
This change adds back logic to normalize NuGet versions so they align
with what NuGet allows and includes unit tests to confirm the results
of the NuGet version normalization function.
=> Allow NuGet version divergence from Semantic Versioning

.vscode/settings.json
Enables flake8 linting in .vscode/settings.json since it is required
in this repo. This will help developers find linting issues locally in
VS Code.
=> .vscode/settings.json: Enable flake8 linting

edk2toolext/environment/plugin_manager.py
This series makes two main changes:
1. [Update usage of deprecated loading APIs](https://github.com/tianocore/edk2-pytool-extensions/commit/49a954c5153d0e8acba8bca88e1b8ef962acd885)
Fixes #337
Plugins are currently loaded in the `_load()` function in
plugin_manager.py by using the `imp` standard library:
https://docs.python.org/3/library/imp.html
The first sentence of the library documentation states the following:
```
Deprecated since version 3.4, will be removed in version 3.12: The
imp module is deprecated in favor of importlib.
```
This means, `imp` will be removed in the next Python release.
Therefore, this change updates the code to use `importlib` standard
library as recommended by the `imp` documentation.
The code follows the recipe recommended by the `importlib`
documentation to …
=> Plugin Loader Updates [Rebase & FF]

edk2toolext/invocables/edk2_pr_eval.py
Paths are currently returned from various functions and compared in
`get_packages_to_build()`. This change updates the paths to be
represented with `Path` objects so path comparison can leverage
the `Path` object equality method to perform the comparison more
robustly than with raw strings.
=> edk2_stuart_pr_eval: Improve robustness of path comparisons

docs/usability/environment_variables.md, edk2toolext/environment/uefi_build.py, edk2toolext/tests/test_uefi_build.py
Closes #340
Adds two optional environment variables that, if specified, will be
used in lieu of the `build` command and its parameters during build.
1. `EDK_BUILD_CMD` - If present, the absolute path to an application
to use for the edk build process that will be invoked instead of
`build`. This is primarily used to allow a tool to wrap around
`build` such that it will eventually call `build` internally.
3. `EDK_BUILD_PARAMS` - If present, these parameters will be passed
to the build command. This is primarily used to pair wrapper-
specific parameters with the wrapper passed in `EDK_BUILD_CMD`.
From a practical standpoint, these are the minimum changes needed
in the build tools to allow the CodeQL CLI to be invoked as a build
wrapper.
Signed-off-by: Michael Kubacki …
=> Allow build wrappers

.github/ISSUE_TEMPLATE/bug_report.yml
Lists the Python versions supported for bug fixes in the bug reporting form.
This is to make it obvious what Python versions are officially supported for bug fixes when a bug is filed.
Contributes to https://github.com/tianocore/edk2-pytool-extensions/issues/345
=> bug_report.yml: Add supported Python versions

.github/workflows/doc-release.yml, docs/user/requirements.txt, readme.md
Adds a github action that executes on a release that deploys the documentation to the pages site.
Example Execution on fork:
Action: https://github.com/Javagedes/edk2-pytool-extensions/actions/workflows/doc-release.yml
Site: https://javagedes.github.io/edk2-pytool-extensions/
=> Add Documentation Deployment Action

edk2toolext/environment/uefi_build.py
This change adds close_fds=False to RunCmd when launching the build.
This is necessary to enable GNU make's job control to pass through. GNU make's job control is implemented using tokens on file descriptor.  If the file descriptors remain open, a GNU make calling stuart_build can communicate with a GNU make called by stuart_build.  However, Python's Popen closes file descriptors by default.
A similar change will be proposed in edk2's build.py, completing the connection from the calling make to the called make.
=> Set close_fds=False when building

docs/contributor/python_release.md, setup.py
Adds a required minimum version of python during pypi release that is mirrored on pypi.org so that it is obvious what python versions are supported for edk2-pytool-extensions.
Additionally adds a new contributor doc file that specifies all files that must be updated when a new minor version of python is released.
Signed-off-by: Joey Vagedes [joeyvagedes@microsoft.com](mailto:joeyvagedes@microsoft.com)
=> Add required python version for pypi

.cspell.json, edk2toolext/environment/self_describing_environment.py, edk2toolext/tests/test_self_describing_environment.py, requirements.txt, setup.py
Closes #367
Git worktrees are a standard, well-defined git feature. See:
https://git-scm.com/docs/git-worktree
The Self-Describing Environment (SDE) currently does not recognize
git worktrees which means it fails with multiple descriptors present
since the worktree is a copy/variation of the base repo.
The SDE should recognize git worktrees and not load descriptors from
the worktrees if they are not the active workspace.
=> Respect git worktrees in the SDE

docs/user/features/extdep.md, edk2toolext/environment/extdeptypes/git_dependency.py, edk2toolext/environment/repo_resolver.py, edk2toolext/tests/test_git_dependency.py, edk2toolext/tests/test_repo_resolver.py
Short commit id's were partially supported in regards to the repo_resolver and git_dependency (ext_dep). This PR adds full support for both and adds tests to ensure they remain supported.
Resolves #236 
Signed-off-by: Joey Vagedes <joeyvagedes@microsoft.com>
=> Synchronize short commit id support

edk2toolext/base_abstract_invocable.py
Adds additional information to the Runtime error produced by the SDE when external dependencies are out of date.
=> platform build SDE failure description

integration_test/Shared_Keywords.robot
Integration tests are failing as a bug was found in QEMU, which has a fix, but is not available until version 8 of QEMU. As this version is not available yet, a temporary workaround was added to allow QEMU to boot in the meantime, which is being applied in this PR.
=> Add Temporary fix to integration tests

docs/user/requirements.txt, edk2toolext/environment/extdeptypes/git_dependency.py, edk2toolext/environment/external_dependency.py, edk2toolext/invocables/edk2_platform_build.py, edk2toolext/tests/test_edk2_update.py, edk2toolext/tests/test_self_describing_environment.py
Adds two separate ways to skip verification of external dependencies.  This is to enable co-development of feature repos that are downloaded as external dependencies instead of submodules.
1. Adds a --noverify flag to stuart_build which will skip verification for all external dependencies for that single run
2. Adds a state flag in the extdep_state.yaml file, verify, that by default is true, but can be set to false to disable verification indefinitely for that external dependency.
Closes #415
=> Add ability to skip verification of external dependencies

edk2toolext/nuget_publishing.py, edk2toolext/tests/test_nuget_publish.py
Previously the NuGet config file required a dummy license value to
be present if `--CustomLicensePath` was given. This change removes
the dummy value being required.
Co-authored-by: Joey Vagedes <joeyvagedes@microsoft.com>
=> nuget_publishing: Make `license` entry in config file optional

edk2toolext/nuget_publishing.py
This message is somewhat prominent since it is shown whenever
a nuget failure code is returned.
"commend" to "command"
Fix makes it easier to find in logs, etc.
=> nuget_publishing: Fix logging message typo

edk2toolext/nuget_publishing.py, edk2toolext/tests/test_nuget_publish.py
NuGet packages can associate a package with source repositories using
the `repository` metadata element.
The following for optional attributes are allowed per the corresponding
nuspec version:
- `type` (4.0+)
- `url` (4.0+)
- `branch` (4.6+)
- `commit` (4.6+)
See the following nuspec reference for more info:
https://learn.microsoft.com/en-us/nuget/reference/nuspec#repository
The GitHub NuGet registry (among others) can use this information to
associate a given package with the specified source content.
See the following GitHub doc for more info:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry
This change adds support for the `repository` element in both the
`New` (set in config file) and `Pack` (change at cmd line) commands
so it …
=> nuget_publishing: Add repository metadata support

azure-pipelines/templates/pytest-test-steps.yml
Updates the release pipeline unit testing to match that of the github action for CI. Removes the ability for the release pipeline to upload unit testing results as this is handled by the github action.
=> Update release pipeline unit testing

requirements.txt, setup.py
Updates the required dependencies for PyPi. Notably we now require edk2-pytool-library to be greater than 0.14.0 and pefile to be greater than 2023.2.7 due to the detected security issue.
Additionally fixes a bug where we were getting our pyyaml requirement from edk2-pytool-library rather than specifying it here. If someone installed only edk2-pytool-extensions and not edk2-pytool-library, they may be missing that requirement.
=> Update pypi required dependencies

edk2toolext/bin/nuget.py
Updates edk2-pytool-extensions from downloading NuGet 5.10.0 to
6.4.0 as many functional and security bugs have been addressed
during this time.
See the NuGet release notes for more detailed information:
https://learn.microsoft.com/en-us/nuget/release-notes/nuget-6.4
=> edk2toolext/nuget: Download NuGet 6.4.0 (latest release)

edk2toolext/environment/shell_environment.py, edk2toolext/tests/test_shell_environment.py
Add an exception to `set_shell_var()` when var_data is None as it is not supported. It will throw an error when it attempts to set os.environ[var_name] = None. Adds this information to the pydocs for the function.
=> shell_environment: set_shell_var() exception

edk2toolext/environment/var_dict.py, edk2toolext/tests/test_var_dict.py
Non valued build variables could incorrectly be created when specifying a variable's value be "" (var_dict.SetValue("VAR_NAME", "", "Comment")). Non-valued build variables should only be created when setting a build variables value to None:
(var_dict.SetValue("VAR_NAME", None, "Comment)).
This commit fixes the check to only create a non-valued build variable when the variable value is None.
=> Non valued build variable bugfix

docs/user/integrate/build.md, docs/user/using/build.md, edk2toolext/edk2_invocable.py, edk2toolext/environment/uefi_build.py, edk2toolext/invocables/edk2_platform_build.py
Adds a method to Edk2Invocable, AddParserEpilog(), that allows an invocable to customize the epilog of the argument parser when --help is used. In particular, Edk2PlatformBuild uses this method to append platform specified critical build env variables so that developers no longer need to dig through the code to see what build customizations are available.
Example output:
`stuart_build -c Platforms\QemuQ35Pkg\PlatformBuild.py --help`
`C:\src\mu_tiano_platforms\Platforms\QemuQ35Pkg> py PlatformBuild.py --help`
```cmd
options:
-h, --help            show this help message and exit
--SKIPBUILD, --skipbuild, --SkipBuild
Skip the build process
--SKIPPREBUILD, --skipprebuild, --SkipPrebuild
Skip prebuild process
--SKIPPOSTBUILD, --skippostbuild, --SkipPostBuild
Skip postbuild process
--FLASHONLY, …
```
=> Add CLI env information to the argument parser --help

.vscode/settings.json, edk2toolext/environment/extdeptypes/git_dependency.py, edk2toolext/tests/test_var_dict.py
Resolves two deprecation warnings and adds back in pytests prepending the path to the tests folder with the workspace path.
=> Pytest updates [REBASE&FF]

requirements.txt, setup.py
Older versions of Cryptography are vulnerable to CVE-2023-0286, which is due to the fact that earlier versions bundle a pre-compiled version of openssl that has a known vulnerability noted in https://www.openssl.org/news/secadv/20230207.txt and https://www.openssl.org/news/secadv/20221213.txt.
Previously, the cryptography package version was downloaded from pyopenssl, however it is best that we specify the version ourselfs.
=> Update Cryptography requirement to at least 39.0.1

edk2toolext/environment/repo_resolver.py, edk2toolext/invocables/edk2_setup.py, edk2toolext/tests/test_edk2_setup.py
If `stuart_setup` was called with the `--force` option when the submodules aren't initialized (either new clone or they were deinit'd), the setup would fail. This fixes that problem.
=> Fixed setup --force when submodules don't exist

edk2toolext/environment/repo_resolver.py
Removes the -z flag when using git worktree list --porcelain and reverts
the required git version back to 2.11 due to many linux based systems
not coming with git 2.36 or greater as a standard git version.
=> Remove z flag for git worktree list porcelain

edk2toolext/environment/repo_resolver.py
In some scenarios, the origin branch does not exist; due to this hardcoding the URL to be the origin URL can fail. In this scenario, we default to the first existing remote's URL.
=> repo_resolver.py: `repo_details()` to use first remote if origin does not exist

edk2toolext/bin/nuget.py, edk2toolext/environment/extdeptypes/nuget_dependency.py, edk2toolext/tests/test_nuget_dependency.py, integration_test/Shared_Keywords.robot, setup.py
Resolves two CI failures in edk2-pytool-extensions:
Integration tests were failing due to the addition of the command line
build variable CODE_COVERAGE being set to true by default. This adds the
flag and sets it to false in integration tests as this execution is a
build plugin and outside the scope of edk2-pytool-extensions.
With recent changes to pip, using a method from the package during the
setup of the package is no longer supported. Due to this, it was decided
to move when we download NuGet to when we first attempt to use it. This
has multiple benifits as we now no longer download NuGet, even if the
user is supplying their own version of NuGet, and our download NuGet
functionality remains inside the package and easily testable, rather
then an extra function inside of setup.py …
=> Resolve CI failures [REBASE&FF]

integration_test/Shared_Keywords.robot, integration_test/azure-pipelines/windows-robot-integration-test.yml
Updates Qemu to 2023.4.24 (which is version 8.0.0) and reverts the temporary change that allows qemu to boot until qemu 8.0.0 was released
=> integration_tests: Update Qemu and revert 71a2d5a [REBASE&FF]

edk2toolext/edk2_logging.py
The False positive rate of API keys being filtered out was a detriment to developer productivity per #502. This commit reduces the API key to be only lowercase a-z as NuGet API keys generated from NuGet.org are generated as all lowercase. This should reduce the amount of false positives noted, specifically false positives due to the long folder names in the build output folder.
=> edk2_logging.py: increase specificity of NuGet API key

edk2toolext/environment/extdeptypes/nuget_dependency.py
Adds mono to the front of the Nuget command when the OS detected is MacOS or FreeBSD.
=> Enable Nuget.exe on MacOS and FreeBSD

azure-pipelines/templates/build-publish-whl-steps.yml
The `Build a wheel` azure pipeline step fails as the `-m` flag specifying we are calling a python module rather than a python file was not included. This results in the building of the wheel failing. This commit adds the -m flag to the command.
=> azure-pipelines: build a wheel update

pyproject.toml
Updates the project's readme `content-type` from markdown to text/markdown as specified by PEP 621. Due to the incorrect content-type, the readme was not being properly displayed on PyPi releases.
=> pyproject.toml: update readme content-type

edk2toolext/environment/extdeptypes/git_dependency.py, edk2toolext/environment/external_dependency.py, edk2toolext/invocables/edk2_platform_build.py, tests.unit/test_edk2_update.py, tests.unit/test_self_describing_environment.py
The ability to skip external dependency verification was added with the anticipation of additional developer workflows, however those workflows have evolved over time and the ability to skip external dependency verification is no longer necessary. As it is no longer necessary, it only adds additional complexity to the codebase and confusion to developers attempting to use it. Removing this functionality is the best way forward, but can always be reconsidered or reworked in the future if necessary.
=> Revert skip verification

edk2toolext/environment/uefi_build.py, tests.unit/test_uefi_build.py
Adds error logging and gracefully exit when either TARGET or TOOL_CHAIN_TAG has not been set in the environment.
=> uefi_build: missing env error handling

edk2toolext/edk2_logging.py, tests.unit/test_edk2_logging.py
Adds a regex that detects `fatal error` in the compiler output and logs the line as an error.
Example:
`BrotliCompress.c:20:10: fatal error: ./brotli/c/common/constants.h: No such file or directory`
=> edk2_logging: add gcc fatal error regex

edk2toolext/environment/plugintypes/uefi_helper_plugin.py
Logs the message at error level so it is more likely to be seen by the user in their console so they know what to do.
Before:
```
> stuart_update -c .\Platforms\QemuQ35Pkg\PlatformBuild.py TOOL_CHAIN_TAG=VS2022
SECTION - Init Self Describing Environment
SECTION - Loading Plugins
WARNING - Unable to register Supervisor Policy Maker
Traceback (most recent call last):
...
Exception: One or more helper plugins failed to load.
```
After:
```
> stuart_update -c .\Platforms\QemuQ35Pkg\PlatformBuild.py TOOL_CHAIN_TAG=VS2022
SECTION - Init Self Describing Environment
SECTION - Loading Plugins
WARNING - Unable to register Supervisor Policy Maker
ERROR - Function MakeSupervisorPolicy already registered from plugin file D:\src\mu_tiano_platforms\Features\MM_SUPV\MmSupervisorPkg\SupervisorPolicyTools\S …
```
=> uefi_helper_plugin.py: Log plugin load exception message at error level

docs/user/features/logging.md, edk2toolext/edk2_logging.py, tests.unit/test_edk2_logging.py
This commit turns secrets filtering off by default, and automatically turns it on when a CI build is detected. This is detected by the environment variable CI or TF_BUILD existing and being set to true, which is automatically set in a github action or azure pipeline respectively.
integration tests confirmed logging automatically enabled:
`DEBUG:root:Detected CI Build on Azure Pipelines. Secrets Filtering Enabled.`
Closes #565
=> edk2_logging: Secrets filtering off by default

edk2toolext/environment/external_dependency.py, tests.unit/test_edk2_update.py
Improve the logging done when either a downloaded external dependency is host_specific and does not support the local host, or the folder for the local host has been deleted.
Closes #549
=> external_dependency: unsupported host logging

edk2toolext/environment/uefi_build.py, edk2toolext/invocables/edk2_pr_eval.py, tests.unit/test_edk2_setup.py
Resolves deprecation warnings from edk2-pytool-library to update parsers to use SetEdk2Path() instead of SetBaseAbsPath() and SetPackagePaths()
=> resolve deprecation warnings

edk2toolext/invocables/edk2_pr_eval.py, tests.integration/edk2_stuart_pr_eval.robot, tests.integration/mu_stuart_pr_eval.robot
Policy 5 is used when a library INF has been changed. Policy 5 will parse each package's dsc (Found via `<pkg>.ci.yaml`.`PrEval`.`DscPath`) and mark a package to be built if that package has a dependency on the changed library INF.
Consuming repo's must update each package's ci.yaml file to now include a new top-level section "PrEval" with an entry "DscPath". This will be the package's DSC used to compile all components and libraries the package provides.
``` yaml
{
"PrEval" : {
"DscPath": "path/to/dsc"
}
}
```
=> edk2_pr_eval: Add Policy 5

.github/dependabot.yml
Updates the frequency of checks to once a week, Mondays at 01:00 UTC.
It was noted that for any given release of edk2-pytool-extensions, that multiple dependencies were updated multiple times, which is a waste of maintainer time. This moves the checks to once a week at Monday, to be reviewed and merged every Monday morning.
=> dependabot.yml: Update frequency of checks

edk2toolext/environment/repo_resolver.py
When resolving a repository dependency, if the URL of the existing repository does not match the URL of the actual dependency, an error is printed to the user stating there is a mismatch. A bug was found in the code that prints this error. The attribute trying to be accessed did not exist because there was an interface change in how that information is accessed.
This bugfix updates the logic to access the information the correct way.
=> repo_resolver: bugfix error printing

edk2toolext/edk2_logging.py
an invalid logging config was set because a log message was registered before the logging was set to edk2 requirements. When this happens, a basic config is applied, which causes other configs not to be applied.
closes #586
=> edk2_logging: bugfix invalid logging config set

edk2toolext/environment/repo_resolver.py
repo_details() was missing information on a repository's submodules and remotes. This information is now populated with this PR.
closes #600
=> repo_resolver: repo_details missing information

edk2toolext/windows/secureboot/secureboot_audit.py
Allow the tool to dump other secure boot variables.
=> add other secure boot variables

edk2toolext/environment/extdeptypes/nuget_dependency.py
When a nuget package fails to download due to an authorization error, additional logging is provided to help the user understand the problem and possible solutions. The message informs the user to either install a credential provider (because the package requires authorization) or to run the command themselves to provide the credentials manually.
The logging appears as follows, per failed NuGet Package:
=> nuget_dependency: authorization failure logging

edk2toolext/environment/plugintypes/ci_build_plugin.py
Removes an unecessary log that logs a file path before it is appended to the returned list. As this is the only logging in the function and the only way files get added to the list, a user can log the list of their own accord.
closes #581
=> ci_build_plugin: remove unecessary logging

edk2toolext/environment/extdeptypes/web_dependency.py, tests.unit/test_web_dependency.py
The zipfile module does not retain the individual file permissions when extracting files, even though the file permission metadata is present - whereas the tarfile does. This change restores each file's permission to what it was zipped with. 
Confirmed mu_tiano_platforms builds when changing BaseTools to the zip extdep.
closes #579
=> web_external_dependency: restore zipped file permissions

edk2toolext/invocables/edk2_pr_eval.py
Given that PR eval runs before dependencies are downloaded, there will be instances where files used in the dsc are not present. This can be tolerated by setting NoFailMode, which just results in the parser moving onto the next line when the parsing fails.
=> edk2_pr_eval: Policy 5: allow dsc parse failures

edk2toolext/capsule/__init__.py, edk2toolext/capsule/capsule_tool.py, edk2toolext/capsule/signing_helper.py
`__init__.py` is missing from edk2toolext/capsule, which causes the module to not be found on local edit installs of the project (i.e. `pip install -e .`). This commit adds in the expected file.
=> edk2toolext.capsule: add __init__.py

edk2toolext/edk2_invocable.py, edk2toolext/environment/multiple_workspace.py, edk2toolext/environment/plugin_manager.py, edk2toolext/environment/uefi_build.py, pyproject.toml
This commit enables (forces) deprecation warnings to be displayed for external code consumed by the stuart invocable to include the Platform module (typically PlatformBuild.py, CISettings.py) and any plugin (CIBuild, Helper, UefiBuild). This is so that consumers of edk2-pytool-extensions and edk2-pytool-library are made aware of deprecations in parts of the codebase that don't have (1) tests via pytest / unittest that automatically display deprecations or (2) would not typically turn on deprecation warnings themselves.
This commit deprecates `MultipleWorkspace`, consumed by `uefi_build` and used by external code, in favor of Edk2Path. `self.mws` will temporarily exist in `uefi_build`, but `self.edk2path` has been made available for consumers to easily transition and resolve the …
=> Deprecate mws [REBASE&FF]

docs/user/features/codeql.md, edk2toolext/codeql.py, mkdocs.yml, tests.unit/test_codeql.py
Adds a new file that contains functions are intended to ease repo
integration with CodeQL, ensure consistent command-line usage across
repos, and define standard scopes that other plugins and tools can
depend on for CodeQL operations.
=> Add CodeQL helper functions

edk2toolext/edk2_logging.py, tests.unit/test_edk2_logging.py
Adds the ability to detect rust build errors and print them at the end of the build when the build fails.
=> edk2toolext/edk2_logging.py: Log rust errors

.github/ISSUE_TEMPLATE/bug_report.yml, .github/workflows/VariableProducer.yml, azure-pipelines/templates/basic-setup-steps.yml, docs/contributor/python_release.md, pyproject.toml, readme.md, tests.integration/azure-pipelines/windows-robot-integration-test.yml
Updates all documentation and testing to use python 3.10, 3.11, and 3.12.
Additionally adds a python-requires section to the pyproject.toml, to ensure a proper error if someone tries to pip install edk2-pytool-library v0.19.0 on a python version less than 3.10
=> Update Supported Python versions to 3.10, 3.11, and 3.12

.cspell.json, edk2toolext/edk2_invocable.py, edk2toolext/invocables/edk2_ci_build.py, edk2toolext/invocables/edk2_platform_build.py, tests.unit/test_edk2_invocable.py
Adds support to report Rust tool versions in the version aggregator so the versions are available in the Build Tools Report.
Also prints the version to the logger at info level similar to other versions so it is part of the build output.
---
Example output in the build console:
```
INFO - cargo version: 1.73.0
INFO - cargo make version: 0.37.2
INFO - rustc version: 1.73.0
```
Example output in the HTML build report:
=> Add Rust tool version reporting

.cspell.json, edk2toolext/environment/reporttypes/coverage_report.py
Adds the additional functionality to the coverage report:
1. Generate xml data for source files that do not have coverage data with the `--full` flag. Using this flag requires the `-ws` flag is pointing to the workspace root, so that the files can be found for code counting.
2. Adds the ability to "flatten"reports with the `--flatten` flag. This flag causes the report to place all source files together, rather than grouping them by INF. This results in different coverage data as duplicate sources files are removed (which can occur when a certain source file is used by multiple INFs). 
3. Changes the `name` attribute for a file to be the package path relative path. This is because report generator tools that consume the coverage.xml file combine coverage data for source files with the same …
=> coverage_report: Add additional functionality

edk2toolext/environment/reporttypes/coverage_report.py
coverage_report attempted to split by both separator types (":" and ";"), however this caused a bug due to the fact that windows paths contain ":" to specify the drive letter, which resulted in invalid package paths.
This change splits by os.sep, which is the correct way to split paths.
=> coverage_report: split packagepaths by os.sep

edk2toolext/environment/reporttypes/templates/usage_report_template.html, edk2toolext/environment/reporttypes/usage_report.py
Updates usage report (`stuart_report usage`) with the following:
1. Adds a third pie chart that is the combined totals from the library and components pie charts.
2. Adds an additional three pie charts that show total line count used by a repository rather than INF count.
3. Moves the INF pie charts and source pie charts into their own respective tabs in the report, leaving the Summary tab to only provide important environment information.
4. Updates the data table tab to also include total line count of all source files used by the INF in the table.
=> Reports: Usage Report: Add additional data

edk2toolext/edk2_invocable.py, edk2toolext/invocables/edk2_multipkg_aware_invocable.py
Enables the invocable to display it's command line arguments if `-h` or `--help` is provided, regardless of if it has a configuration file.
``` cmd
WARNING: Some command line arguments may be missing. Provide a platform module file to ensure all command line arguments are present.
usage: stuart_build [-h] [-c PLATFORM_MODULE]
options:
-h, --help            show this help message and exit
-c PLATFORM_MODULE, --platform_module PLATFORM_MODULE
Provide the Platform Module relative to the current working directory.This should contain a BuildSettingsManager instance.
```
```cmd
WARNING: Some command line arguments may be missing. Provide a platform module file to ensure all command line arguments are present.
usage: stuart_ci_build [-h] [-c PLATFORM_MODULE] [-p PACKAGELIST] [-a REQUESTED_ARCH] …
```
=> Show invocable's help even without a config file

edk2toolext/environment/extdeptypes/web_dependency.py
The file permissions issue that was fixed via #608 was specifically targeting Linux systems (as seen in the tests, that only test for Linux), however the permissions fix-up was applied regardless of operating system. This change ensures that the fixup is only applied on Non windows systems.
=> Only restore file permissions on Linux

edk2toolext/edk2_invocable.py
Changes made in #639 to ensure the invocable displayed their command line arguments when a build module was not provided failed to test the critical scenario of ensuring the help message was still displayed when a build module was provided.
The help command line argument is consumed during the first pass of the command line argument parser, so when the build module is found, registered, and the parser is re-executed, the help argument is no longer present to trigger the help message display.
This commit fixes the issue by adding the "--help" command line argument to the arguments to be parsed if it was detected in the first parse.
closes #708
=> edk2_invocable: print help message when build module provided

.cspell.json, .vscode/settings.json, edk2toolext/edk2_report.py, edk2toolext/environment/reporttypes/component_report.py, edk2toolext/environment/reporttypes/coverage_report.py, edk2toolext/environment/reporttypes/usage_report.py, edk2toolext/invocables/edk2_parse.py, pyproject.toml
edk2-pytool-library v0.20.0 provides a re-work of Edk2DB to use an ORM (sqlalchemy) instead of sqlite3 directly to help lower the barrier of entry for using the database functionality.
This pull request updates the slight usage change to Edk2DB, but is mainly focused on updating the reports for stuart_report to use the ORM entity models for getting the needed data from the database rather than raw SQL queries.
=> edk2-pytool-library v0.20.0 integration

.github/workflows/doc-release.yml
Updates deploy-pages github action to 4.0.1 which, from deploy-pages should resolve the build error being seen is #732 
resolves #732
=> Update deploy-pages to 4.0.1

edk2toolext/environment/reporttypes/usage_report.py, edk2toolext/invocables/edk2_parse.py
Adds a new command line flag to stuart_parse (`-S`, `--source-stats`) to enable performing analysis on source files (for calculating lines of code, etc). This is disabled by default as it greatly increases the parse time.
=> stuart_parse: add flag to perform source analysis.

.github/workflows/CIRunner.yml, azure-pipelines/templates/markdown-lint-steps.yml, readme.md
Upgrades markdownlint-cli to 0.39.0 from 0.32.2.
The release is currently failing as the release pipeline that comes from edk2-pytool-extensions does not have a locked version of markdown lint. This upgrades markdownlint-cli to 0.39.0, which will be the locked version in edk2-pytool-extensions.
=> upgrade markdownlint-cli

edk2toolext/edk2_invocable.py, tests.unit/test_edk2_setup.py
This change fixes a bug in the edk2_invocable.py script where an invalid command line argument would not cause the script to exit with an error.
This occured due to a change that enabled non-valued environment variables to be passed to the script. The result of this change was that any invalid command line argument would be added as a non-valued environment variable rather than triggering the error handling.
This commit makes it such that any non-valued environment variable cannot start with a '-' character, as that is reserved for argparse arguments.
=> edk2_invocable: Bugfix for bad argument handling

edk2toolext/environment/reporttypes/coverage_report.py
Originally, both a --by-package and --by-platform flag was created to describe the types of coverage reports able to be generated, and allow for grouping the command line arguments based on these two flags.
With the adding of the ability to filter on packages for the platform report, the --by-package flag no longer has any special arguments and can be deprecated. Due to this, this change also removes the --by-package flag, making it the default behavior, which is overridden by --py-platform.
=> coverage_report: Allow package filtering for --by-platform

edk2toolext/edk2_invocable.py, tests.unit/test_edk2_setup.py
1. updates edk2_invocable.py to catch any unexpected argument that start with either a "-" or "/" rather than just "-". This is due to the fact that "/" is a common argument prefix for executables.
2. Changes the RuntimeError exception to a print statement and an exit command as this is an expected possible user error and a print of the backtrace is unnecessary.
=> edk2_invocable.py: catch invalid arguments

docs/user/using/ci.md, edk2toolext/invocables/edk2_ci_build.py
Functionality currently exists to skip the execution of a specific plugin with `<PluginName>=skip` in the command line.  This change adds the ability to do the opposite, by setting the `-d` (or `--disable-all`) flag and then specifying the plugins to run with `<PluginName>=run`.
example:
`stuart_ci_build -c .pytool/CISettings.py --disable-all SpellCheck=run`
=> Add the ability to run only the requested plugins

edk2toolext/environment/extdeptypes/nuget_dependency.py
edk2toolext\environment\extdeptypes\nuget_dependency.py
line number: 172
self.nuget_cache_path = return_string.strip().strip("global-packages: ")
This is an incorrect usage of the strip method. This will cause failures if the nuget dependency path ends with "e"
For example if the NuGet cache path is: "C:\nuget_cache", the second strip method will return an invalid path.
The second strip("global-packages: ") call is intended to remove the characters in the set "global-packages: " from both ends of the string. This set includes each individual character: 'g', 'l', 'o', 'b', 'a', 'l', '-', 'p', 'a', 'c', 'k', 'a', 'g', 'e', 's', ':', and ' ' (space). It does not treat "global-packages: " as a single substring to remove.
This method then removes these characters from the beginning and the end …
=> Fix incorrect usage of strip method while accessing the nuget_cache_path

edk2toolext/edk2_invocable.py
Improve the in-line documentation for edk2_invocable.py, which improves the quality of documentation at https://www.tianocore.org/edk2-pytool-extensions/
=> edk2_invocable.py: Improve documentation

edk2toolext/edk2_invocable.py
Improve the documentation for `GetActriveScopes` and `GetSkippedDirectories` to specify that these are used by the `self_descriving_environment` (SDE) to ignore parts of the workspace and to control which custom components (`path_env`, `ext_dep`, and `plug_in` are loaded for a given execution.
=> edk2_invocable.py: Improve documentation for SDE related functions

edk2toolext/environment/reporttypes/coverage_report.py, tests.unit/test_repo_resolver.py
Check if the file exists in the workspace before passing to pygount for source code analysis. If it does not exist, skip the file.
=> coverage_report: Gracefully handle missing file

edk2toolext/invocables/edk2_parse.py
Arguments passed to `stuart_parse` are not provided to the instantiated `UefiBuilder`, so any platform that relies on command line arguments to set some build configuration will fail.
=> edk2_parse: allow UefiBuilder to parse args

edk2toolext/environment/plugin_manager.py
edk2-pytool-library is failing to update on edk2 due to an importlib issue on edk2-pytool-extensions (see: https://github.com/tianocore/edk2/actions/runs/9368163753/job/25789491929?pr=5722). From a google search, the issue is that we should be importing as `import importlib.util` not `import importlib`: https://stackoverflow.com/questions/66797668/module-importlib-has-no-attribute-util
=> Update how importlib is imported 

edk2toolext/edk2_logging.py, edk2toolext/environment/repo_resolver.py
* Fix an issue with parameter handling in repo_resolver that prevented "branch", "shallow", and "reference" parameters from being passed to git clone operations.
* Updated logging configuration to allow better tracing of repo_resolver operations for future debugging of similar issues.
=> Fix parameter handling in repo_resolver and update logging configuration.

edk2toolext/environment/repo_resolver.py
When resolving a repo with submodules via the repo_resolver::checkout() method, the reference argument (if appropriate) was not used for submodule updates as part of resolution. This PR adds support for the reference argument to allow references to be used throughout the resolution process.
=> Add reference argument to submodule update --init invocations

edk2toolext/invocables/edk2_ci_build.py
Adds a new command line argument, `-f`, `--fail-fast` to stuart_ci_build that will cause the script to exit immediately if any ci plugin fails.
`stuart_ci_build -c .\.pytool\CISettings.py -p MdeModulePkg --disable-all  NestedPackageCheck=run `
` stuart_ci_build -c .\.pytool\CISettings.py -p MdeModulePkg --disable-all  NestedPackageCheck=run --fail-fast`
=> ci_build: Add fail-fast option

.cspell.json, edk2toolext/edk2_invocable.py, edk2toolext/invocables/edk2_multipkg_aware_invocable.py, edk2toolext/invocables/edk2_platform_build.py
1. If a configuration file is provided, will provide all available options for architecture (-a), package (-p) and target (-t).
2. Ensures that the CLI env guidance is provided to the user even If no configuration file is provided (bugfix).
3. Updates some general help text to be more clear.
=> invocables: Update --help information

docs/user/features/rust_environment.md, edk2toolext/environment/rust.py, edk2toolext/rust_environment.py, tests.unit/test_rust_environment.py
Adds helpers for checking if a firmare environment is ready to build Rust.
The primary purpose of the functionality in rust_environment is to be used in a build plugin wrapper. However, the public functions may be used in other contexts as well.
=> Add Rust Environment module

docs/user/features/environment_variables.md, docs/user/features/extdep.md, docs/user/features/plugin_manager.md, docs/user/index.md, docs/user/integrate/build.md, docs/user/integrate/manage.md, docs/user/integrate/reporting.md, docs/user/using/build.md, docs/user/using/ci.md, docs/user/using/install.md, docs/user/using/reporting.md, mkdocs.yml
[MkDocs v1.5.0](https://github.com/mkdocs/mkdocs/releases/1.5.0) Updated how links were evaluated (See "Expanded Validaton of links" section). Before 1.5.0, most links in our documentation were left "untouched" as they either started or ended with a `/`.
> ... links that started with `/` ("absolute") and links that _ended_ with `/` were left as is ...
However these links are now properly evaluated, which broke most links in edk2-pytool-extensions documentation. With this new evaluation, All of our links that started absolute (`/`) were now linking relative to `tianocore.org` instead of `tianocore.org/edk2-pytool-extenisons`.
This pull request updates the documentation to utilize the newly introduced `absolute_links` validation setting to be `relative_to_docs` which updates absolute paths …
=> Documentation: Fix all broken links

.github/workflows/VariableProducer.yml, edk2toolext/environment/extdeptypes/nuget_dependency.py
As described in [external_dependency.py#L38](https://github.com/tianocore/edk2-pytool-extensions/blob/1e4ddee16145c262b96c67bd442124563400d8d6/edk2toolext/environment/external_dependency.py#L38), the `name` configuration is the name of the ext_dep, used to name the folder the ext_dep will be unpacked into. When the nuget external dependency was added, `name` also became the name of the package you are downloading, which tightly couples the name of the package and the folder path. This means there is no way to name the folder something other than the package name, which can be necessary in some situations.
This change provides a backwards compatible way to de-couple the package name from the folder name by introducing a new, optional config for nuget dependencies, `package`. `package` will …
=> nuget_dependency: Allow path override

docs/user/tools/using_image_validation_tool.md
Updates the documentation in using_image_validation_tool.md to fix the current breakage in the documentation that is causing CI to fail.
=> image_validation: Update documentation

docs/user/integrate/porting.md
Ran through the porting steps on a clean WSL and found a few minor corrections to the documentation.
=> Minor updates to the porting readme

.github/workflows/UnitTestRunner.yml
ubuntu-latest, now ubuntu-24.04 no longer has mono installed in the runner image.
This commit updates the UnitTestRunner.yml to install mono before running the tests.
=> Install mono on ubuntu-latest

.github/ISSUE_TEMPLATE/bug_report.yml, .github/workflows/VariableProducer.yml, docs/contributor/developing.md, docs/contributor/python_release.md, pyproject.toml, readme.md, tests.integration/azure-pipelines/windows-robot-integration-test.yml
This commit removes support for python 3.10. Attempting to install v0.28.0 of edk2-pytool-extensions using a python version less than 3.11 will result in an error from pip along the lines of `ERROR: Could not find a version that satisfies the requirement ...`
If your platform cannot upgrade to 3.11 or above, continue using a version of edk2-python-extensions less than v0.28.0. Otherwise upgrade your version of platform to 3.11 or greater. If edk2-pytool-library is not automatically downloaded with edk2-pytool-extensions, then you also need to ensure that edk2-pytool-library is v0.22.0 or greater
=> Python support: drop 3.10, add 3.13

edk2toolext/capsule/pyopenssl_signer.py
per pyopenssl deprecation notice, the crypto module is being deprecated. Per the pyopenssl documentation, the cryptography module is the recommended replacement. This commit updates the pyopenssl_signer to use the cryptography module.
This deprecation was discovered as Ubuntu-24.04 images are missing the `crypto` module.
https://www.pyopenssl.org/en/stable/api/crypto.html
=> pyopenssl_signer: Use cryptography

edk2toolext/environment/rust.py
There have been too many instances of issues manually installing cargo-make. These issues occur because cargo-make does not upload a Cargo.lock file for releases, and our rust repositories always being on an old rust version. This results in the latest versions of some crates being pulled in, which may have their minimum supported version of rust higher than the version we use.
To improve the user experience, lets just have the user install the binaries instead of attempting to compile.
=> rust.py: Use cargo-binstall

edk2toolext/environment/rust.py, tests.unit/test_rust_environment.py
Currently, the plugin supports locating tools in a `[tool]` section. Other scripts and flows have been built around `[tools]`. This change finds tools from either section.
=> Allow [tool] or [tools] section in Rust Env Checker

edk2toolext/environment/extdeptypes/az_cli_universal_dependency.py, tests.unit/test_az_cli_universal_dependency.py
1. If the `azure-devops` extension is not installed, provide a URL with installation instructions. This link can directly be clicked in many shell environments.
2. If an error occurs running the Azure CLI then show the error message to the user. This often has helpful instructions for what needs to be done to resolve the error. Example shown below.
Before:
```
raise Exception("{0} failed with Return Code: {1}".format(cmd, returncode_str))
Exception: az artifacts universal download --organization https://dev.azure.com/Organization/
--feed FEED --name NAME --version 0.0.1 --path "PATH" failed with Return Code: 0x00000001
```
After:
```
raise Exception(
Exception:
Command "az artifacts universal download --organization https://dev.azure.com/Organization/
--feed FEED --name NAME --version …
```
=> az_cli_universal_dependency: Enhance error messaging

edk2toolext/edk2_invocable.py, edk2toolext/environment/uefi_build.py
Improves the verbosity command line argument for stuart commands in the following ways:
1. Moves when the flag is registered, so that the flag can be seen with the --help flag, even if a configuration file is not used.
2. Passes the verbosity flag to the edk2 build command.
Additionally, as a part of (2), platforms can now also control verbosity of EDKII Build in their platform configuration files via the EDK2_BUILD_VERBOSE env variable.
Resolves #935
=> improve verbosity flag override

edk2toolext/environment/extdeptypes/az_cli_universal_dependency.py, tests.unit/test_az_cli_universal_dependency.py
Search az cli universal package output for json data if the StreamIO has other output from the command. Sometimes the results output will have extra data from the az cli command. This needs to be ignored before attempting to load the results as json data.
=> az_cli_universal_dependency.py: Manage results output for non-Json data

edk2toolext/environment/extdeptypes/az_cli_universal_dependency.py
Minor update to reduce the verbosity of log when the results data contains non-Json information. This failure should be seen as non-critical. After attempting to parse the data and the results data is still bad, then a failure and error print is enforced.
=> az_cli_universal_dependency.py: Lower logging verbosity when az download command results contain non-Json data

tests.unit/test_secureboot_audit.py
The test currently writes a "uefi_org_revocations2.json" file to repo workspace which shows up as a tracked file addition in git. It does not appear this file is actually used, so remove it from the test.
=> test_secureboot_audit: Remove unnecessary file written outside test dir

edk2toolext/base_abstract_invocable.py, edk2toolext/environment/repo_resolver.py, edk2toolext/environment/self_describing_environment.py, edk2toolext/environment/uefi_build.py, edk2toolext/invocables/edk2_ci_build.py, edk2toolext/invocables/edk2_ci_setup.py, edk2toolext/invocables/edk2_parse.py, edk2toolext/invocables/edk2_platform_build.py, edk2toolext/invocables/edk2_pr_eval.py, edk2toolext/invocables/edk2_setup.py, edk2toolext/invocables/edk2_update.py
Adds `debug` level messages with the pattern "Time to" to log the time taken to perform important tasks. This provides greater insight into overall stuart execution time and allows results to be compared for regressions and across environments.
---
A build log can be filtered to "Time to" messages to get a condensed view of build time (from mu_tiano_platforms build):
```
Time to Get Git Version: 0.125 s
Time to Check If Repo is Dirty: 1.808 s
Time to Check for Worktrees: 2.413 s
Time to Gather Env Files: 5.288 s
Time to Bootstrap Environment: 11.939 s
Time to Verify Environment: 0.314 s
Time to Load Plugins: 1.205 s
Time to Start Invocable: 13.503 s
Time to Kick Off Platform Build: 7.243 s
Time to ParseTargetFile: 0.007 s
Time to ParseToolsDefFile: 0.036 s
Time to ParseDscFile: 0.908 s …
```
=> Add high-level performance data

edk2toolext/base_abstract_invocable.py, edk2toolext/edk2_invocable.py, edk2toolext/edk2_logging.py, edk2toolext/environment/repo_resolver.py, edk2toolext/environment/self_describing_environment.py, edk2toolext/environment/uefi_build.py, edk2toolext/invocables/edk2_ci_build.py, edk2toolext/invocables/edk2_ci_setup.py, edk2toolext/invocables/edk2_parse.py, edk2toolext/invocables/edk2_platform_build.py, edk2toolext/invocables/edk2_pr_eval.py, edk2toolext/invocables/edk2_setup.py, edk2toolext/invocables/edk2_update.py
Adds a separate logger for logging stuart performance measurements.
Developers (both of core stuart, and of plugins) can use `edk2_logging.performance_measurement()` to record performance measurements when the feature is enabled with the `--log-perf` flag, which is disabled by default.
=> edk2_logging: Add separate perf measurement logs

edk2toolext/environment/extdeptypes/git_dependency.py, edk2toolext/environment/repo_resolver.py, edk2toolext/invocables/edk2_ci_setup.py, tests.unit/test_git_dependency.py, tests.unit/test_repo_resolver.py
GetRequiredSubmodules() vs GetDependencies()
GetRequiredSubmodules() allows a recursive/omnicache configuration parameter to be passed. 
The configuration parameter determines if --recursive is passed when the submodule is cloned.
GetDependencies() does not have configuration for this type of scenario.
A Dependency from GetDependencies will always attempt to resolve **ALL** submodules that are contained in the repo.
This presents a problem when a submodule contains their own dependency as well. The example run into is:
SecurityPkg => libspdm
libspdm => openssl
openssl => gost-engine
gost-engine => libprov
```
{
"Path": "Common/MU_TIANO",
"Url": "https://github.com/microsoft/mu_tiano_plus.git",
"Branch": "dev/202502",
},
```
```
{
"Path": "Common/MU_TIANO",
"Url": …
```
=> Improve configuration options for GetDependencies.

edk2toolext/environment/repo_resolver.py
--reference and --recurse-submodules cannot be used at the same time.
Resolve issue introduced in #966 that allowed the parameter to be used at the same time during git clone with omnicache.
=> repo_resolver: fix case of reference and recurse being mutually exclusive.

pyproject.toml
- Fix this deprecation warning:
> Please use a simple string containing a SPDX expression for
`project.license`.
By following guidance at:
https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-files
- Fix this deprecation warning:
> Please consider removing the following classifiers in favor of a SPDX license expression:
License :: OSI Approved :: BSD License
By removing the license classifier.
- Prevent pyproject from failing if documentation is built in the workspace with this error:
> error: Multiple top-level packages discovered in a flat-layout: ['site', 'edk2toolext'].
By explicitly setting `py-modules` to `edk2toolext`.
=> pyproject.toml: Fix deprecations

edk2toolext/environment/repo_resolver.py, edk2toolext/invocables/edk2_setup.py, tests.unit/test_repo_resolver.py
Use case:
In a PlatformBuild.py file, GetRequiredSubmodules() is implemented to list
the required submodules that need to be downloaded for the platform build.
These submodules, today, will only have the True/False configuration option, which will 
recurse all submodules, including the submodules submodules.
(Example: mu_tiano_plus includes LibSpdm, which includes submodule openssl, which includes submodule pyca/cryptography)
But, repo dependent, the submodules of a submodule are not required to build/use the functionality.
Add an optional configuration option that will allow specifying a CISettings file and only the submodules in the settings file will be downloaded.
Test Environment:
Modify mu_tiano_platform's PlatformBuild.py:
`RequiredSubmodule("MU_BASECORE", True,), …
=> Adding limited cloning capabilities to stuart_setup

edk2toolext/environment/repo_resolver.py
When checking out a PR using the gh command, the tracking branch may not be associated with any of the current remotes. This causes a python exception determining the URL of the remote associated with the PR branch when running stuart commands.
However, the URL to the repo the PR was created from can be determined by parsing the tracking_branch() and removing the branch name from the end of the tracking_branch().
=> environment/repo_resolved: Support branches from gh pr checkout

edk2toolext/edk2_invocable.py, tests.unit/test_nuget_dependency.py
The following warning is now present (with Python 3.12.10):
```
/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages
edk2toolext/edk2_invocable.py:31:
UserWarning: pkg_resources is deprecated as an API.
See https://setuptools.pypa.io/en/latest/pkg_resources.html.
The pkg_resources package is slated for removal as early as 2025-11-30.
Refrain from using this package or pin to Setuptools<81.
import pkg_resources
```
This change replaces it with `importlib`.
=> edk2_invocable: Fix `pkg_resources` deprecation warning

edk2toolext/edk2_invocable.py
This commit results in only the first version of a pip package found on the path being used as the version, even if multiple versions exist in the distribution list because it exists in multiple path locations. If using a venv environment, the path to those pip modules is prepended, so it should theoretically always be correct.
=> edk2_invocable: Register one version per pip package

docs/user/features/sde.md
Cleans up some of the documentation to be tables so that it is better formatted and easier to read.
Before:
After:
=> docs/sde: Clean up format to be table

docs/user/features/plugin_manager.md
The previous format did not properly display sub-indents as sub-indents in the final documentation. This commit updates each main indent to now be a section header, with indents to follow for each statement.
=> docs/plugin_manager: Clean up invalid indent format.

edk2toolext/invocables/edk2_pr_eval.py
Process build variables as policy in Policy 4:
- First, consider variables in build files such as those in the [Defines] section of the DSC.
- Second, consider variables defined in the `GetPlatformDscAndConfig()` implementation. This is analogous to `SetPlatformEnv()` for PR Eval.
- Third, update the list of variables based on the dictionary returned from `GetAllBuildKeyValues()` which contains the build variables resolved against the current target.
The *second* and *third* steps above are now used as the "input" variables to the DSC parser.
---
Also describes the `PrEvalSettingsManager.GetPlatformDscAndConfig` API in more detail to clarify how it is used.
---
Note: Will use the updated edk2-pytool-library commit from https://github.com/tianocore/edk2-pytool-library/pull/750 after that …
=> edk2_pr_eval: Consider build variables in Policy 4 [Rebase & FF]

edk2toolext/perf/fpdt_parser.py, tests.unit/test_fpdt_parser.py
Format output xml and align GUID format for fpdt_parser.
Apply `minidom` to format the output xml of the `fpdt_parser.py` to improve readability.
The script was not adding entries to FBDT table so the output is not a proper tree structure.
Before it was:
```
|- fbpt_header
|- fbpt_record
|- fbpt_record
```
Now it is:
```
|- fbpt_header
|   |- fbpt_record
|   |- fbpt_record
```
it can be properly consumed by `perf_report_generator.py` to generate perf report. Before this change there will be 0 entries in the report because the input structure doesn't match what the script needs.
Update the GUID format for different entries to make sure the output GUID format stay the same and can be recognized by the perf_report_generator.py.
Add xml formatter to make sure the output xml more readable. …
=> Format output xml and align GUID format for fpdt_parser

edk2toolext/environment/uefi_build.py
Removed @classmethod decorators from specific methods in the `UefiBuilder` class. These methods are intended to be overridden by subclasses and do not require class-level binding. Keeping them as class methods was unnecessary and led to confusion for developers implementing or extending `UefiBuilder`.
=> Removed @classmethod decorators from methods intended to be overridden by subclasses
