tianocore/edk2-pytool-extensions

setup.py
=> Missing cli tool for nuget publishing.

edk2toolext/environment/extdeptypes/web_dependency.py, edk2toolext/tests/test_web_dependency.py
=> [Bug] Fix web dependency for single file downloads

edk2toolext/edk2_invocable.py
=> Added helpful message when we use the wrong invokable type on a given py file

edk2toolext/omnicache.py
commit 8fe4829d on mu_pip_environment
=> Allow remotes to be renamed via config file

edk2toolext/environment/extdeptypes/web_dependency.py, edk2toolext/tests/test_web_dependency.py
Add test coverage for sha256 on web dependency
Resolve bug of case sensitivity 
Issue #65
=> Bug: Fix web dependency hash compare

edk2toolext/edk2_invocable.py, edk2toolext/environment/version_aggregator.py, edk2toolext/invocables/edk2_ci_build.py, edk2toolext/invocables/edk2_platform_build.py
=> VersionAggregator improvements (pip version and python version)

docs/usability/creating_invocable.md, docs/usability/using_settings_manager.md, edk2toolext/base_abstract_invocable.py, edk2toolext/edk2_invocable.py, edk2toolext/invocables/edk2_ci_build.py, edk2toolext/invocables/edk2_ci_setup.py, edk2toolext/invocables/edk2_platform_build.py, edk2toolext/invocables/edk2_setup.py, edk2toolext/invocables/edk2_update.py
Breaking change to edk2_setup.py settings API
=> Submodule recursion support to optimize initialization process

readme.md
Update readme with version 0.11.0 highlights
=> Prepare 0.11.0 Release

edk2toolext/edk2_logging.py
=> [Bug] Stop suppressing warnings from non root loggers

edk2toolext/edk2_invocable.py
=> When an exception occurs when loading settings managers, print out the exception

edk2toolext/invocables/edk2_pr_eval.py, setup.py
Detect which packages need to be tested based on PR contents
=> Add new stuart_pr_eval tool which allows PR optimized testing

edk2toolext/environment/repo_resolver.py
=> Added message in Ci setup to let user know what dependency is being cloned

docs/usability/using_nuget_publishing.md, edk2toolext/bin/nuget.py, edk2toolext/environment/extdeptypes/nuget_dependency.py, edk2toolext/nuget_publishing.py, edk2toolext/tests/test_nuget_dependency.py, edk2toolext/tests/test_nuget_publish.py
This will allow -beta -rc and -alpha to nuget versions
Details can be found here: https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages
=> Add tags to nuget version validation

edk2toolext/environment/extdeptypes/git_dependency.py, edk2toolext/tests/test_git_dependency.py
=> [Bug #124] fixed version aggregation for Git Dependencies

readme.md
Move current status section up in order
=> Update readme section ordering

edk2toolext/environment/plugintypes/uefi_helper_plugin.py
previously, when plugins would fail, there would be literally zero information on what failed. This outputs that to the log
=> [Feature] added exception handling for plugins

.cspell.json, docs/usability/using_extdep.md, docs/usability/using_linux.md, docs/usability/using_wsl_or_linux.md
We had some feedback that pytools wasn't doing a great job of supporting non windows platforms. We updated the document to include information for correctly installing Mono.
=> [Documentation] updated WSL and Linux document

edk2toolext/base_abstract_invocable.py
=> [Bug] fix log level for summary on builds

edk2toolext/invocables/edk2_update.py
=> [Bug] Return failure count instead of 0 so that update failure will be apparently in pipeline scenarios

docs/features/feature_sde.md, docs/usability/creating_invocable.md, docs/usability/porting_a_platform.md, docs/usability/using_plugin_manager.md
Previously there were several references to Project Mu and some of the information on the SDE was out of date.
Fixes #133
=> [Documentation] remove project mu references 

edk2toolext/invocables/edk2_multipkg_aware_invocable.py
=> [Bug] strip trailing right side slash on package paths

edk2toolext/edk2_invocable.py, edk2toolext/invocables/edk2_ci_build.py, edk2toolext/invocables/edk2_ci_setup.py, edk2toolext/invocables/edk2_multipkg_aware_invocable.py, edk2toolext/invocables/edk2_platform_build.py, edk2toolext/invocables/edk2_pr_eval.py, edk2toolext/invocables/edk2_setup.py, edk2toolext/invocables/edk2_update.py
Make APIs more consistent and don't override functions in Settings Managers.
Raise Exceptions for required functions
Set safe defaults for optional functions
=> Clean up invokable SettingsManagers and hierarchy

MANIFEST.in, edk2toolext/environment/plugintypes/ci_build_plugin.py, edk2toolext/tests/test_ci_build_plugin.py
REF: #189 
Clean up comments, add typing, and add check for type of parameter ignorelist
Add Unit test
=> Update ci build WalkDirectoryForExtension to use exceptions

.cspell.json, integration_test/.gitignore, integration_test/ReadMe.md, integration_test/Shared_Keywords.robot, integration_test/edk2_core_ci.robot, integration_test/edk2_platform_ci.robot, integration_test/edk2_stuart_pr_eval.robot, integration_test/mu_core_ci.robot, integration_test/mu_stuart_pr_eval.robot
Some of the pytool extensions are hard to get good unit test coverage.  This is due to extensions often being CLI tools and depending on a large set of files on the file system (UEFI edk2 code tree). 
To improve testing and quality this adds the IntegrationTest folder.  This contains RobotFramework based scripts and tests that can be run by a developer to validate prior to a release.
=> Add support for RobotFramework based automated integration testing

edk2toolext/bin/nuget.py
Some server cred issues should be resolved.  Also just good to keep current.
=> Update Nuget to version 5.7.0

setup.py
=> Upgrade pyyaml to 5.3.1

edk2toolext/omnicache.py, edk2toolext/tests/test_omnicache.py
Resolves a couple of issues discovered when testing omnicache 0.11 at scale:
1. #264 
2. #263
=> Omnicache bugfixes

docs/usability/using_extdep.md, edk2toolext/environment/extdeptypes/az_cli_universal_dependency.py, edk2toolext/environment/external_dependency.py, edk2toolext/tests/test_az_cli_universal_dependency.py
See https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops for details on universal packages
=> Add initial support for Azure CLI universal packages as ext_dep type

codecov.yaml, docs/features/feature_extdep.md, docs/usability/environment_variables.md, docs/usability/using_extdep.md, edk2toolext/environment/extdeptypes/nuget_dependency.py, edk2toolext/environment/extdeptypes/web_dependency.py, edk2toolext/environment/external_dependency.py, edk2toolext/environment/self_describing_environment.py, edk2toolext/tests/test_external_dependency.py, edk2toolext/tests/test_nuget_dependency.py
Needs some more documenting, but it seems to work well.
Also solves some of the problems that we've had with "malformed" Nuget cache.
=> Create an ExtDep cache for any Stuart extdep type

docs/usability/using_image_validation_tool.md, edk2toolext/image_validation.py, edk2toolext/tests/test_image_validation.py
Update section alignment requirements in line with #296 . Also fixed a few misc. issues.
=> Update section alignment requirements

BasicDevTests.py, ConfirmVersionAndTag.py, docs/using.md, edk2toolext/base_abstract_invocable.py, edk2toolext/capsule/capsule_helper.py, edk2toolext/edk2_invocable.py, edk2toolext/environment/conf_mgmt.py, edk2toolext/environment/environment_descriptor_files.py, edk2toolext/environment/extdeptypes/git_dependency.py, edk2toolext/environment/plugin_manager.py, edk2toolext/environment/plugintypes/ci_build_plugin.py, edk2toolext/environment/plugintypes/uefi_helper_plugin.py, edk2toolext/environment/repo_resolver.py, edk2toolext/environment/self_describing_environment.py, edk2toolext/environment/uefi_build.py, edk2toolext/environment/var_dict.py, edk2toolext/invocables/edk2_ci_build.py, edk2toolext/invocables/edk2_multipkg_aware_invocable.py, edk2toolext/invocables/edk2_platform_build.py, edk2toolext/invocables/edk2_pr_eval.py, edk2toolext/nuget_publishing.py, edk2toolext/omnicache.py, edk2toolext/tests/test_git_dependency.py, edk2toolext/tests/test_omnicache.py, integration_test/edk2_stuart_pr_eval.robot, integration_test/mu_stuart_pr_eval.robot
Fix flake8 E275 failures which requires a space after a keyword (in particular, the **assert**, **if**, **elif**, and **else** keywords)
Fix integration test failures due to recent changes in both Project Mu and EDK2
=> Fix CI Failures

integration_test/Shared_Keywords.robot, integration_test/edk2_stuart_pr_eval.robot, integration_test/mu_stuart_pr_eval.robot
=> Fix typos in robot files

.github/workflows/ci.yml, docs/contributor/developing.md, docs/user/requirements.txt, readme.md
Adds a check to the github action that verifies mkdocs builds with no errors or warnings.
=> Add a check to verify mkdocs builds

docs/user/integrate/build.md, docs/user/using/build.md
Adds documentation about how to pass build values through stuart to the build command.
Signed-off-by: Joey Vagedes <joeyvagedes@microsoft.com>
=> Add documentation on build values

docs/user/features/creating_invocable.md, docs/user/features/logging.md, edk2toolext/base_abstract_invocable.py, edk2toolext/edk2_invocable.py, edk2toolext/edk2_logging.py, edk2toolext/invocables/edk2_ci_build.py, edk2toolext/tests/test_edk2_logging.py, readme.md
Remove markdown logging support.
Signed-off-by: Joey Vagedes joeyvagedes@microsoft.com
=> Remove markdown logging

docs/user/features/using_linux.md, docs/user/using/install.md, readme.md
Updates documentation regarding versions of ubuntu from 18.04 and 20.04 to 20.04 and 22.04. Also updates the git documentation to reflect the new required version.
=> Update Ubuntu and git documentation

.github/dependabot.yml
Adds github-actions to the list of dependencies dependabot checks for.
=> dependabot.yml: Add GitHub actions

docs/user/requirements.txt
Removes the requirements.txt file in favor of the requirements described in the pyroject.toml file.
=> documentation: remove requirements.txt

MANIFEST.in
Exclude folders and files from final package uploaded to PyPI
=> MANFIEST.in: additional excludes

.github/dependabot.yml, docs/contributor/python_release.md, tests.integration/ReadMe.md, tests.integration/azure-pipelines/windows-robot-integration-test.yml
Updates all places that reference integration_test/* to reference tests.integration/
=> tests.integration: update directory

readme.md
=> readme: make documentation url more visible

edk2toolext/environment/extdeptypes/az_cli_universal_dependency.py, tests.unit/test_az_cli_universal_dependency.py
In some circumstances, the az extdep may be a compressed file that may need to decompressed and provided to the consumer.
=> az_cli_ext_dep: Add ability to unzip download

edk2toolext/environment/repo_resolver.py, tests.unit/test_repo_resolver.py
Sometimes the underlying git operations fails when checking if the repo is dirty. Like this:
```
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "C:\src\ws\Scripts\stuart_build.exe\__main__.py", line 7, in <module>
File "C:\src\ws\venv\Lib\site-packages\edk2toolext\invocables\edk2_platform_build.py", line 183, in main
Edk2PlatformBuild().Invoke()
File "C:\src\ws\venv\Lib\site-packages\edk2toolext\base_abstract_invocable.py", line 210, in Invoke
(build_env, shell_env) = self_describing_environment.BootstrapEnvironment(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\src\ws\venv\Lib\site-packages\edk2toolext\environment\self_describing_environment.py", line 381, in BootstrapEnvironment
build_env = …
```
=> repo_resolver: Retry on git dirty repo checks
